
/* Categorias*/
CREATE TABLE IF NOT EXISTS CATEGORY
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(80),
    categoryid INTEGER references CATEGORY(id)
);
INSERT INTO CATEGORY(NAME, description, CATEGORYID) 
VALUES 
('Role', 'Hace referencia al catálogo de roles identificados dentro de la organización.', NULL),
('Estudiante', 'Estudiantes en general', 1),
('Docente', 'Docentes en general', 1),
('Administrador', 'Administrador del sistema',1),
('Invitado', 'Invitados en general',1),

('Keywords', 'Hace referencia al catálogo de palabras clave de un post', NULL),
('Emprendimiento', 'palabra clave', 6),
('Docencia', 'palabra clave',6),
('Investigacion', 'palabra clave', 6),
('Innovación', 'palabra clave', 6);


/*Usuarios*/
CREATE TABLE IF NOT EXISTS USERS
(
    ci VARCHAR(10) UNIQUE PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    lastname VARCHAR(80) NOT NULL,
    dateofbirth DATE,
    role INTEGER references CATEGORY(id),
    status BOOLEAN DEFAULT true 
);

/*Credenciales*/
CREATE TABLE IF NOT EXISTS CREDENTIALS
(
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    userid VARCHAR(10) references USERS(ci)
);


/*Publicaciones*/

CREATE TABLE IF NOT EXISTS POSTS
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR,
    body TEXT,
    autorid VARCHAR(10) references USERS(ci),
    createdat TIMESTAMP
);

/*Publicaciones-keywords*/
CREATE TABLE IF NOT EXISTS POSTS_HAS_KEYWORDS
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idpost integer references POSTS(id),
    keyword integer references CATEGORY(id)
);

INSERT INTO USERS(CI, NAME, LASTNAME, DATEOFBIRTH, ROLE)
VALUES ('1105587388','Richard', 'Arrobo', '1998-07-03', 2);


INSERT INTO CREDENTIALS(EMAIL, PASSWORD, USERID)
VALUES('krarrobo1@utpl.edu.ec', 'qwerty009', '1105587388');


-- POSIBLE EDICION DE LA TABLA


-- CREATE TABLE IF NOT EXISTS CATEGORYTEST
-- (
-- 	category VARCHAR(10) NOT NULL,
--     id integer,
--     name VARCHAR(50) NOT NULL,
--     description VARCHAR(80),
-- 	primary key(category,id)
-- );

-- INSERT INTO CATEGORYTEST(CATEGORY, ID ,NAME, description) 
-- VALUES 
-- ('Role',1,'Estudiante', 'Estudiantes en general'),
-- ('Role',2,'Docente', 'Docentes en general'),
-- ('Role',3,'Administrador', 'Administrador del sistema'),
-- ('Role',4,'Invitado', 'Invitados en general'),

-- ('Keywords',1,'Emprendimiento', 'palabra clave'),
-- ('Keywords',2,'Docencia', 'palabra clave'),
-- ('Keywords',3,'Investigacion', 'palabra clave'),
-- ('Keywords',4,'Innovación', 'palabra clave');